#!/bin/bash

# Be aware that this script only provides a fixed configuration
# for a single node GPU cluster and without memory constraints

sudo apt-get install munge slurm-wlm

HOSTNAME=$(hostname -s)

echo "
# slurm.conf file generated by bootstrap_slurm_ubuntu1804
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ControlMachine=$HOSTNAME
#ControlAddr=
#
#MailProg=/bin/mail
MpiDefault=none
#MpiParams=ports=#-#
ProctrackType=proctrack/pgid
ReturnToService=1
SlurmctldPidFile=/var/run/slurm-llnl/slurmctld.pid
#SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm-llnl/slurmd.pid
#SlurmdPort=6818
SlurmdSpoolDir=/var/lib/slurm-llnl/slurmd
SlurmUser=slurm
#SlurmdUser=root
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
SwitchType=switch/none
TaskPlugin=task/none
#
#
# TIMERS
#KillWait=30
#MinJobAge=300
#SlurmctldTimeout=120
#SlurmdTimeout=300
#
#
# SCHEDULING
FastSchedule=1
SchedulerType=sched/backfill
#SchedulerPort=7321
SelectType=select/cons_res
SelectTypeParameters=CR_CPU
#
#
# LOGGING AND ACCOUNTING
AccountingStorageType=accounting_storage/none
ClusterName=cluster
#JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
#SlurmctldDebug=3
SlurmctldLogFile=/var/log/slurm-llnl/slurmctld.log
#SlurmdDebug=3
SlurmdLogFile=/var/log/slurm-llnl/slurmd.log
#
#
# COMPUTE NODES
" > slurm.conf

NUM_SOCKETS=$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)
NUM_CORES=$(cat /proc/cpuinfo | grep "cpu cores" | sort | uniq | grep -o "[0-9]*")
NUM_THREADS=$(cat /proc/cpuinfo | grep "siblings" | sort | uniq | grep -o "[0-9]*")
NUM_THREADS_PER_CORE=$(expr $NUM_THREADS / $NUM_CORES)

HAS_GPU=1
if ! command -v nvidia-smi &> /dev/null
then
    HAS_GPU=0
fi

if [ $HAS_GPU -eq 1 ];then
    echo "GresTypes=gpu" >> slurm.conf
    GPU_NAME=$(nvidia-smi | grep -o "^|[ ]*0  [A-Za-z]*" | grep -o "[A-Za-z]*" | tr '[:upper:]' '[:lower:]')
    GPU_COUNT=$(ls /dev/nvidia* | grep "nvidia[0-9]" | wc -l)
    echo "NodeName=ip-192-168-0-15 Sockets=$NUM_SOCKETS CoresPerSocket=$NUM_CORES ThreadsPerCore=$NUM_THREADS_PER_CORE State=UNKNOWN Gres=gpu:$GPU_NAME:$GPU_COUNT" >> slurm.conf
    GPU_DEVICES=$(ls /dev/nvidia* | grep "nvidia[0-9]")
    echo "" > gres.conf
    for f in $GPU_DEVICES; do
        echo "Name=gpu Type=$GPU_NAME  File=$f" >> gres.conf
    done;
else
    echo "NodeName=$HOSTNAME Sockets=$NUM_SOCKETS CoresPerSocket=$NUM_CORES ThreadsPerCore=$NUM_THREADS_PER_CORE State=UNKNOWN" >> slurm.conf
fi

echo "PartitionName=debug Nodes=$HOSTNAME Default=YES MaxTime=INFINITE State=UP" >> slurm.conf

sudo systemctl enable slurmctld.service
sudo systemctl enable slurmd.service
